name: @NAME@
description: Messaging Channels API
version: @VERSION@
author: @AUTHOR@
main: edgruberman.bukkit.messagemanager.Main
commands:
    messagemanager:
        description: Manage core settings related to this plugin
        permission: messagemanager.messagemanager
        usage: |
            /<command> reload - Reloads configuration for the plugin
    timestamp:
        description: Manage timestamp for messages
        aliases: [ts, stamp]
        permission: messagemanager.timestamp
        usage: |
            /<command>[ get][ <Player>] - Display current timestamp
            /<command> reset[ <Player>] - Revert timestamp to default
            /<command> on[ <Player>] - Enable timestamp
            /<command> off[ <Player>] - Disable timestamp
            /<command> pattern([ get][ <Player>]| set[ <Player>] <Pattern>) - Edit date/time pattern
            /<command> format([ get][ <Player>]| set[ <Player>] <Format>) - Edit timestamp appearance in message
            /<command> timezone([ get][ <Player>]| set[ <Player>] <TimeZone>) - Edit time zone
    timezone:
        description: Shortcut for /timestamp timezone
        aliases: tz
        permission: messagemanager.timezone
        usage: |
            /<command>[ <TimeZone>] - Display or configure time zone
permissions:
    messagemanager.messagemanager:
        description: Can use messagemanager command
        default: false
    messagemanager.messagemanager.reload:
        description: Can use reload action of messagemanager command
        default: op
        children:
            messagemanager.messagemanager: true
    messagemanager.timestamp.get:
        description: Can use get action of timestamp command
        default: true
        children:
            messagemanager.timestamp.pattern.get: true
            messagemanager.timestamp.format.get: true
            messagemanager.timestamp.timezone.get: true
    messagemanager.timestamp.self:
        description: Can use all actions of timestamp command
        default: false
        children:
            messagemanager.timestamp.get: true
            messagemanager.timestamp.pattern.set: true
            messagemanager.timestamp.format.set: true
            messagemanager.timestamp.timezone.set: true
            messagemanager.timestamp.reset: true
            messagemanager.timestamp.toggle: true
    messagemanager.timestamp.get.player.*:
        description: Can use get action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp.get: true
            messagemanager.timestamp.pattern.get.player.*: true
            messagemanager.timestamp.format.get.player.*: true
            messagemanager.timestamp.timezone.get.player.*: true
    messagemanager.timestamp.player.*:
        description: Can use all actions of timestamp command for any player
        default: op
        children:
            messagemanager.timestamp.self: true
            messagemanager.timestamp.get.player.*: true
            messagemanager.timestamp.pattern.set.player.*: true
            messagemanager.timestamp.format.set.player.*: true
            messagemanager.timestamp.timezone.set.player.*: true
            messagemanager.timestamp.reset.player.*: true
            messagemanager.timestamp.toggle.player.*: true
    messagemanager.timestamp:
        description: Can use the timestamp command
        default: false
    messagemanager.timestamp.pattern:
        description: Can use pattern action of timestamp command
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.pattern.get:
        description: Can use get pattern action of timestamp command
        default: false
        children:
            messagemanager.timestamp.pattern: true
    messagemanager.timestamp.pattern.set:
        description: Can use set pattern action of timestamp command
        default: false
        children:
            messagemanager.timestamp.pattern.get: true
    messagemanager.timestamp.format:
        description: Can use format action of the timestamp command
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.format.get:
        description: Can use get format action of timestamp command
        default: false
        children:
            messagemanager.timestamp.format: true
    messagemanager.timestamp.format.set:
        description: Can use set format action of timestamp command
        default: false
        children:
            messagemanager.timestamp.format.get: true
    messagemanager.timezone:
        description: Can use timezone shortcut
        default: false
    messagemanager.timestamp.timezone:
        description: Can use timezone action of timestamp command
        default: false
        children:
            messagemanager.timestamp: true
            messagemanager.timezone: true
    messagemanager.timestamp.timezone.get:
        description: Can use get timezone action of timestamp command
        default: false
        children:
            messagemanager.timestamp.timezone: true
    messagemanager.timestamp.timezone.set:
        description: Can use set timezone action of timestamp command
        default: false
        children:
            messagemanager.timestamp.timezone.get: true
    messagemanager.timestamp.reset:
        description: Can use reset action of timestamp command
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.on:
        description: Can use on action of timestamp command
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.off:
        description: Can use the off action of timestamp command
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.toggle:
        description: Can use on and off actions of timestamp command
        default: false
        children:
            messagemanager.timestamp.on: true
            messagemanager.timestamp.off: true
    messagemanager.timestamp.pattern.get.player.*:
        description: Can use get pattern action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.pattern.set.player.*:
        description: Can use set pattern action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp.pattern.get.player.*: true
    messagemanager.timestamp.format.get.player.*:
        description: Can use get format action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.format.set.player.*:
        description: Can use set format action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp.format.get.player.*: true
    messagemanager.timestamp.timezone.get.player.*:
        description: Can use get timezone action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.timezone.set.player.*:
        description: Can use set timezone action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp.timezone.get.player.*: true
    messagemanager.timestamp.reset.player.*:
        description: Can use reset action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.on.player.*:
        description: Can use on action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.off.player.*:
        description: Can use off action of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp: true
    messagemanager.timestamp.toggle.player.*:
        description: Can use on and off actions of timestamp command for any player
        default: false
        children:
            messagemanager.timestamp.on.player.*: true
            messagemanager.timestamp.off.player.*: true