level:
    broadcast: ALL
    send: ALL
    log: ALL
timestamp:
    color: DARK_GRAY
    format: 'HH:mm:ss ' # SimpleDateFormat
broadcast:
    level: INFO
    format: '%3$s%2$s%1$s' # 1 = Message, 2 = Color, 3 = Formatted Timestamp
    log: '[Broadcast] %1$s' # 1 = Formatted Message
send:
    level: INFO
    format: '%3$s%2$s-> %1$s' # 1 = Message, 2 = Color, 3 = Formatted Timestamp
    log: '[Message->%2$s] %1$s'  # 1 = Formatted Message, 2 = Player Name
log:
    level: INFO
    format: '[%2$s] %1$s'  # 1 = Formatted Message, 2 = Plugin Name
colors:
    SEVERE:
        send: RED
        broadcast: DARK_RED
    WARNING:
        send: YELLOW
        broadcast: GOLD
    NOTICE:
        send: LIGHT_PURPLE
        broadcast: DARK_PURPLE
    INFO:
        send: WHITE
        broadcast: WHITE
    STATUS:
        send: GREEN
        broadcast: DARK_GREEN
    EVENT:
        send: GRAY
        broadcast: DARK_GRAY
    CONFIG:
        send: AQUA
        broadcast: DARK_AQUA
    RIGHTS:
        send: BLUE
        broadcast: DARK_BLUE
    FINE:
        send: BLACK
        broadcast: BLACK
    FINER:
        send: BLACK
        broadcast: BLACK
    FINEST:
        send: BLACK
        broadcast: BLACK