send:
    PLAYER:
        level: CONFIG
        format: '-> %1$s' # 1 = Message, 2 = Player Name
        log: '[PLAYER] [%2$s] %1$s' # 1 = Formatted Message, 2 = Player Name
    SERVER:
        level: CONFIG
        format: '%1$s' # 1 = Message, 2 = null
        log: '[SERVER] %1$s' # 1 = Formatted Message, 2 = Server Name
    WORLD:
        level: CONFIG
        format: '[%2$s] %1$s' # 1 = Message, 2 = World Name
        log: '[WORLD] %1$s' # 1 = Formatted Message, 2 = World Name
    CUSTOM:
        level: CONFIG
        format: '[%2$s] %1$s' # 1 = Message, 2 = Channel Name
        log: '[CUSTOM] %1$s' # 1 = Formatted Message, 2 = Channel Name
    LOG:
        level: RIGHTS
        format: '[%2$s] %1$s' # 1 = Message, 2 = Plugin Name
        log: '%1$s' # 1 = Formatted Message, 2 = Plugin Name
timestamp:
    pattern: 'HH:mm:ss' # SimpleDateFormat
    format: '&8%2$s &_%1$s' # 1 = Formatted Message, 2 = Timestamp
    timezone: null
color:
    SEVERE:
        PLAYER: RED
        SERVER: DARK_RED
        WORLD: DARK_RED
        CUSTOM: DARK_RED
        LOG: DARK_RED
    WARNING:
        PLAYER: YELLOW
        SERVER: GOLD
        WORLD: GOLD
        CUSTOM: GOLD
        LOG: GOLD
    NOTICE:
        PLAYER: LIGHT_PURPLE
        SERVER: DARK_PURPLE
        WORLD: DARK_PURPLE
        CUSTOM: DARK_PURPLE
        LOG: DARK_PURPLE
    INFO:
        PLAYER: WHITE
        SERVER: WHITE
        WORLD: WHITE
        CUSTOM: WHITE
        LOG: WHITE
    STATUS:
        PLAYER: GREEN
        SERVER: DARK_GREEN
        WORLD: DARK_GREEN
        CUSTOM: DARK_GREEN
        LOG: DARK_GREEN
    EVENT:
        PLAYER: GRAY
        SERVER: DARK_GRAY
        WORLD: DARK_GRAY
        CUSTOM: DARK_GRAY
        LOG: DARK_GRAY
    RIGHTS:
        PLAYER: BLUE
        SERVER: DARK_BLUE
        WORLD: DARK_BLUE
        CUSTOM: DARK_BLUE
        LOG: DARK_BLUE
    CONFIG:
        PLAYER: AQUA
        SERVER: DARK_AQUA
        WORLD: DARK_AQUA
        CUSTOM: DARK_AQUA
        LOG: DARK_AQUA
    FINE:
        PLAYER: BLACK
        SERVER: BLACK
        WORLD: BLACK
        CUSTOM: BLACK
        LOG: BLACK
    FINER:
        PLAYER: BLACK
        SERVER: BLACK
        WORLD: BLACK
        CUSTOM: BLACK
        LOG: BLACK
    FINEST:
        PLAYER: BLACK
        SERVER: BLACK
        WORLD: BLACK
        CUSTOM: BLACK
        LOG: BLACK
logLevel: RIGHTS
version: @VERSION@